apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-demo
  namespace: argocd
spec:
  description: Kargo-managed demo environments
  sourceRepos:
    - https://github.com/aadi308/Kargo-ArgoCD.git
  destinations:
    - namespace: demo-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
